name: workflow 008

on:
  push:
    branches:
      - main
    paths:
      - '/Dockerfile'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:

    # Generate json for shields.io Endpoint badge
    - name: Generate badge data
      id: badge_data
      run: |
        BADGE_VALUE=$(date -u +'%Y-%m-%d')
        JSON="docker-openssh-build-date-badge.json"
        echo "json=$JSON" >> $GITHUB_OUTPUT
        cat <<EOF > $JSON
        {
          "schemaVersion": 1,
          "label": "build",
          "message": "$BADGE_VALUE",
          "color": "green"
        }
        EOF

    # Upload json from step badge_data 
    # to gist for shields.io Endpoint badge
    - name: Create or update gist
      uses: stellarhub/push-gist-action@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: ${{ vars.GIST_ID }}
        file_path: ${{ steps.badge_data.outputs.json }}
        file_type: text

